# Site Settings
locale                   : "en-US"
title                    : Sebastian Mostek
title_separator          : "-"
subtitle                 : The physicist who ended up with a MechE degree
name                     : Sebastian Mostek
description              : Sebastian Mostek - Projects and CV 
baseurl                  : "/smostek-portfolio"

# Theme and Style
theme: jekyll-theme-minimal
color_scheme: desert # light/default, dark, desert, or aqua

sass:
  style: compressed

# Outputting
permalink: /:categories/:title/

collections:
  pages:
    output: true
  projects:
    output: true
    permalink: /:collection/:path/

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

